<a href="https://colab.research.google.com/github/hrushikesh01/PDS-2303A51788-B12/blob/main/lab_3_14_aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Question 1
import numpy as np

data = np.array([[78, 85, 92, 88],
                 [67, 74, 81, 79],
                 [90, 95, 89, 84],
                 [76, 80, 85, 83]])

row_mean = np.mean(data, axis=1)
col_mean = np.mean(data, axis=0)

std_dev = np.std(data)
variance = np.var(data)

global_max = np.max(data)
global_min = np.min(data)

max_index = np.unravel_index(np.argmax(data), data.shape)
min_index = np.unravel_index(np.argmin(data), data.shape)

print("Data:\n", data)
print("Row-wise mean:", row_mean)
print("Column-wise mean:", col_mean)
print("Standard Deviation:", std_dev)
print("Variance:", variance)
print("Global Max:", global_max, "at index", max_index)
print("Global Min:", global_min, "at index", min_index)


Data:
 [[78 85 92 88]
 [67 74 81 79]
 [90 95 89 84]
 [76 80 85 83]]
Row-wise mean: [85.75 75.25 89.5  81.  ]
Column-wise mean: [77.75 83.5  86.75 83.5 ]
Standard Deviation: 6.9988838395847095
Variance: 48.984375
Global Max: 95 at index (np.int64(2), np.int64(1))
Global Min: 67 at index (np.int64(1), np.int64(0))


In [ ]:
# Question 2
import numpy as np

image = np.random.randint(0, 256, (3, 3, 3), dtype=np.uint8)

red_channel = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel = image[:, :, 2]

avg_red = np.mean(red_channel)
avg_green = np.mean(green_channel)
avg_blue = np.mean(blue_channel)

brightened = np.clip(image + 50, 0, 255)

print("Original Image:\n", image)
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
print("Average Red Intensity:", avg_red)
print("Average Green Intensity:", avg_green)
print("Average Blue Intensity:", avg_blue)
print("Brightened Image:\n", brightened)


Original Image:
 [[[219  53 106]
  [179  82  64]
  [120  94 212]]

 [[248 221 217]
  [170 101  72]
  [ 63   2 139]]

 [[153 192  93]
  [169 186 254]
  [ 18 210 162]]]
Red Channel:
 [[219 179 120]
 [248 170  63]
 [153 169  18]]
Green Channel:
 [[ 53  82  94]
 [221 101   2]
 [192 186 210]]
Blue Channel:
 [[106  64 212]
 [217  72 139]
 [ 93 254 162]]
Average Red Intensity: 148.77777777777777
Average Green Intensity: 126.77777777777777
Average Blue Intensity: 146.55555555555554
Brightened Image:
 [[[ 13 103 156]
  [229 132 114]
  [170 144   6]]

 [[ 42  15  11]
  [220 151 122]
  [113  52 189]]

 [[203 242 143]
  [219 236  48]
  [ 68   4 212]]]
