<a href="https://colab.research.google.com/github/hrushikesh01/PDS-2303A51788-B12/blob/main/lab_2_B12-7aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Question-1
import numpy as np

marks = np.array([
    [85, 78, 92],
    [74, 88, 69],
    [90, 94, 81],
    [65, 70, 60],
    [88, 76, 95]
])

print("Student Marks (2D Array):\n", marks)

average_marks = np.mean(marks)
min_marks = np.min(marks)
max_marks = np.max(marks)

print("\nAverage Marks (Overall):", average_marks)
print("Minimum Marks (Overall):", min_marks)
print("Maximum Marks (Overall):", max_marks)

student3_marks = marks[2]
print("\nMarks of Student 3:", student3_marks)

above_80 = marks > 80
print("\nBoolean Array (True if mark > 80):\n", above_80)

marks_above_80 = marks[marks > 80]
print("\nMarks above 80:", marks_above_80)

subject_wise = marks.T
print("\nSubject-wise Performance (Transposed Array):\n", subject_wise)

subject_avg = np.mean(subject_wise, axis=1)
subject_min = np.min(subject_wise, axis=1)
subject_max = np.max(subject_wise, axis=1)

print("\nSubject-wise Average:", subject_avg)
print("Subject-wise Minimum:", subject_min)
print("Subject-wise Maximum:", subject_max)


Student Marks (2D Array):
 [[85 78 92]
 [74 88 69]
 [90 94 81]
 [65 70 60]
 [88 76 95]]

Average Marks (Overall): 80.33333333333333
Minimum Marks (Overall): 60
Maximum Marks (Overall): 95

Marks of Student 3: [90 94 81]

Boolean Array (True if mark > 80):
 [[ True False  True]
 [False  True False]
 [ True  True  True]
 [False False False]
 [ True False  True]]

Marks above 80: [85 92 88 90 94 81 88 95]

Subject-wise Performance (Transposed Array):
 [[85 74 90 65 88]
 [78 88 94 70 76]
 [92 69 81 60 95]]

Subject-wise Average: [80.4 81.2 79.4]
Subject-wise Minimum: [65 70 60]
Subject-wise Maximum: [90 94 95]


In [ ]:
#Question-2
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "ID": [101, 102, 103, 104, 105],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [48000, 55000, 72000, 45000, 60000]
}

df = pd.DataFrame(data)
print("Initial DataFrame:\n", df)

high_salary = df[df["Salary"] > 50000]
print("\nEmployees with Salary > 50,000:\n", high_salary)

sorted_df = df.sort_values(by="Salary", ascending=False)
print("\nDataFrame Sorted by Salary (Descending):\n", sorted_df)

df["Bonus"] = df["Salary"] * 0.10
print("\nDataFrame with Bonus Column:\n", df)

total_expense = df["Salary"].sum() + df["Bonus"].sum()
print("\nTotal Salary Expense (Including Bonus):", total_expense)

df.to_csv("employee_salary_analysis.csv", index=False)
print("\nData saved to 'employee_salary_analysis.csv'")


Initial DataFrame:
       Name   ID Department  Salary
0    Alice  101         HR   48000
1      Bob  102         IT   55000
2  Charlie  103    Finance   72000
3    David  104         IT   45000
4      Eva  105  Marketing   60000

Employees with Salary > 50,000:
       Name   ID Department  Salary
1      Bob  102         IT   55000
2  Charlie  103    Finance   72000
4      Eva  105  Marketing   60000

DataFrame Sorted by Salary (Descending):
       Name   ID Department  Salary
2  Charlie  103    Finance   72000
4      Eva  105  Marketing   60000
1      Bob  102         IT   55000
0    Alice  101         HR   48000
3    David  104         IT   45000

DataFrame with Bonus Column:
       Name   ID Department  Salary   Bonus
0    Alice  101         HR   48000  4800.0
1      Bob  102         IT   55000  5500.0
2  Charlie  103    Finance   72000  7200.0
3    David  104         IT   45000  4500.0
4      Eva  105  Marketing   60000  6000.0

Total Salary Expense (Including Bonus): 308000.0

Dat